retructure, remove unused script and activate experiment feature

diff --git a/bin/pyenv-universal2 b/bin/pyenv-universal2
--- a/bin/pyenv-universal2
+++ b/bin/pyenv-universal2
@@ -1,5 +1,5 @@
 #!/usr/bin/env bash
-
+set -e
 # ========config==============
 CONFIG_FILE="$(dirname "${BASH_SOURCE[0]}")/pyenv-universal2-config"
 if [[ -f "$CONFIG_FILE" ]]; then
@@ -79,7 +79,7 @@ readonly ARM_ARCH="arm64"
 PYENV_ROOT="${PYENV_ROOT:-$(pyenv root)}"
 readonly PYENV_ROOT
 readonly BASE_COMMAND="pyenv-universal2"
-readonly commands=("build" "merge" "arm64" "x86_64" "test" "update" "version" "custom-brew" "help")
+readonly commands=("build" "merge" "arm64" "x86_64" "collect-deps" "rpath-update" "test" "update" "version" "custom-brew" "help")
 
 # ====== Load Core Script ======
 load_core_script() {
@@ -126,7 +126,6 @@ parse_global_options() {
 # ====== Function ======
 build_command() {
     local python_version="$1"
-    shift
 
     if [[ -z "$python_version" ]]; then
         color_echo "ERROR" "Error: 'build' requires a Python version as an argument." >&2
@@ -153,19 +152,16 @@ build_command() {
         local custom_suffix="${python_version}"
     fi
 
-    local no_clean="$NO_CLEAN"
-
     if ! declare -F universal2-build >/dev/null; then
         log "INFO" "Loading core script for fat binary build"
         load_core_script "universal2-build"
     fi
 
-    build_universal2_python "$python_version" "$custom_suffix" "$no_clean" "$@"
+    build_universal2_python "$python_version" "$custom_suffix"
 }
 
 merge_command() {
     local python_version="$1"
-    shift
 
     if [[ -z "$python_version" ]]; then
         color_echo "ERROR" "Error: 'merge' requires at least one argument." >&2
@@ -186,14 +182,12 @@ merge_command() {
         local custom_suffix="${python_version}"
     fi
 
-    local no_clean="$NO_CLEAN"
-
     if ! declare -F universal2-merge >/dev/null; then
         log "INFO" "Loading core script for merge python"
         load_core_script "universal2-merge"
     fi
  
-    universal2_merge "$python_version" "$custom_suffix" "$no_clean"
+    universal2_merge "$python_version" "$custom_suffix"
 }
 
 single_command() {
@@ -293,12 +287,26 @@ collect-deps_command() {
     universal2_collect_binary "$python_version" "$python_dir"
 }
 
-rpath_command() {
+rpath-update_command() {
     local python_version="$1"
     shift
 
+    local only_int="false"
+    local only_ext="false"
+
+    for arg in "$@"; do
+        case $arg in
+            --int=*) only_int="${arg#*=}" ;;
+            --ext=*) only_ext="${arg#*=}" ;;
+            *)
+                log "WARN" "Unknown argument: $arg"
+                return 1
+                ;;
+        esac
+    done
+
      if [[ -z "$python_version" ]]; then
-        color_echo "ERROR" "Error: 'rpath' requires at least one argument." >&2
+        color_echo "ERROR" "Error: 'rpath' requires at least one argument (python version)." >&2
         exit 1
     fi
 
@@ -314,7 +322,7 @@ rpath_command() {
         load_core_script "universal2-rpath"
     fi
  
-    universal2_update_rpath "$python_version" "$python_dir"
+    universal2_update_rpath "$python_version" "$python_dir" --int="$only_int" --ext="$only_ext"
 }
 
 update_command() {
diff --git a/libexec/tools/u2-utility b/libexec/tools/u2-utility
--- a/libexec/tools/u2-utility
+++ b/libexec/tools/u2-utility
@@ -1,108 +1,20 @@
 #!/usr/bin/env bash
+set -e
 
-path_regex() {
-    if [[ -z "$ARM_BREW_DIR" || -z "$X86_BREW_DIR" ]]; then
-        color_echo "ERROR" "ARM_BREW_DIR or X86_BREW_DIR not set."
-        return 1
+run_if_not_dry() {
+    if [[ "$DRY_RUN" != "true" ]]; then
+        "$@"
+    else
+        color_echo "INFO" "Dry run mode: skipped: $*"
     fi
-    
-    escape_path() {
-        echo "$1" | sed 's/[.[\*^$(){}+?|]/\\&/g'
-    }
-
-    local arm_re x86_re
-    arm_re=$(escape_path "$ARM_BREW_DIR")
-    x86_re=$(escape_path "$X86_BREW_DIR")
-
-    BREW_PATH_REGEX="^(${arm_re}|${x86_re})/(lib|opt|Cellar)"
-}
-
-scan_binaries(){
-    local python_dir="$1"
-
-    find "$python_dir" -type f \( -name "*.dylib" -o -name "*.so" \) -print \
-        -o -type f -exec sh -c '
-            for file; do
-                if file "$file" | grep -qE "Mach-O.*executable"; then
-                    echo "$file"
-                fi
-            done
-        ' sh {} +   
-}
-
-scan_and_extract_fat_binary(){
-    local python_dir="$1"
-    local temp_dir="$2"
-    local output_file="$3"
-
-    : > "$output_file"
-
-    local output_data=""
-
-    while IFS= read -r binary; do
-        [[ -f "$binary" ]] || continue
-     
-        color_echo "INFO" "Processing binary: $binary"
-
-        local binary_name
-        binary_name=$(basename "$binary")
-
-        if ! lipo -info "$binary" | grep -q "fat"; then
-            log "INFO" "$binary is not a fat binary, skipping extraction."
-            continue
-        fi
-
-        local x86_binary="$temp_dir/${binary_name}_x86"
-        local arm_binary="$temp_dir/${binary_name}_arm"
-        if [[ ! -f "$x86_binary" || ! -f "$arm_binary" ]]; then
-            lipo -extract x86_64 "$binary" -output "$x86_binary"
-            lipo -extract arm64 "$binary" -output "$arm_binary"
-        fi
-        output_data+="$binary|$x86_binary|$arm_binary"$'\n'      
-    done < <(scan_binaries "$python_dir")
-    echo -n "$output_data" >> "$output_file"
-}
-
-scan_binary_and_cache(){
-    local python_dir="$1"
-    local output_file="$2"
-
-    : > "$output_file"
-
-    local output_data=""
-
-    while IFS= read -r binary; do
-        [[ -f "$binary" ]] || continue
-
-        color_echo "INFO" "Processing binary: $binary"
-
-        local binary_name
-        binary_name=$(basename "$binary")
-        if ! lipo -info "$binary" | grep -q "fat"; then
-            log "INFO" "$binary is not a fat binary, skipping extraction."
-            continue
-        fi
-        output_data+="$binary"          
-    done < <(scan_binaries "$python_dir")
-    echo -n "$output_data" >> "$output_file"
-}
-
-resign_all_binaries() {
-    local binary_dir="$1"
-    find "$binary_dir" -type f \( -name "*.dylib" -o -name "*.so" -o -name "python3*" \) | while read -r file; do
-        if codesign --force --sign - "$file"; then
-            log "INFO" "Re-signed $file"
-        else
-            color_echo "WARN" "Failed to sign $file"
-        fi
-    done
 }
 
 cleanup_temp() {
     local delete_item="$1"
 
     if [[ -z "$delete_item" || "$delete_item" == "/" ]]; then
-        color_echo "ERROR" "Refusing to delete an empty or root path: '$delete_item'"
+        log "ERROR" "Refusing to delete an empty or root path: '$delete_item'"
+        color_echo "ERROR" "Refusing to delete an empty or root path"
         return 1
     fi
 
@@ -128,13 +40,6 @@ test_binary_for_arch() {
     local arch="$2"
     local binary="${python_path}/bin/python"
 
-    # if arch -$arch "${python_path}/bin/python" --version; then
-    #     log "INFO" "$arch binary test passed successfully."
-    #     return 0
-    # else
-    #     log "WARN" "Warning: $arch binary test failed."
-    #     return 1
-    # fi
     if [[ ! -x "$binary" ]]; then
         log "WARN" "Binary not found or not executable: $binary"
         return 1
@@ -182,16 +87,16 @@ test_binary_conditional() {
     fi
 
     if [[ -z "$arm_test_failed" && -z "$x86_test_failed" ]]; then
-        log "INFO" "Binary is universal2: both ARM64 and x86_64 are present."
+        log "INFO" "Binary is universal2: both ARM64($arm_test_failed) and x86_64($x86_test_failed) are present."
         color_echo "INFO" "Binary is universal2: both ARM64 and x86_64 are present."
     elif [[ -z "$arm_test_failed" ]]; then
-        log "INFO" "Binary is ARM64-only."
+        log "INFO" "Binary is ARM64($arm_test_failed)."
         color_echo "INFO" "Binary is ARM64-only."
     elif [[ -z "$x86_test_failed" ]]; then
-        log "INFO" "Binary is x86_64-only."
+        log "INFO" "Binary is x86_64($x86_test_failed)."
         color_echo "INFO" "Binary is x86_64-only."
     else
-        log "ERROR" "Binary is invalid: neither ARM64 nor x86_64 present."
+        log "ERROR" "Binary is invalid: neither ARM64($arm_test_failed) nor x86_64($x86_test_failed) present."
         color_echo "ERROR" "Binary is invalid: neither ARM64 nor x86_64 present."
         return 1
     fi
diff --git a/libexec/universal2-build b/libexec/universal2-build
--- a/libexec/universal2-build
+++ b/libexec/universal2-build
@@ -1,24 +1,13 @@
 #!/usr/bin/env bash
+set -e
 
-# Load 
 source "$(dirname "${BASH_SOURCE[0]}")/tools/u2-install-python" 
 source "$(dirname "${BASH_SOURCE[0]}")/tools/u2-utility"
-source "$(dirname "${BASH_SOURCE[0]}")/tools/u2-merge-lib-bin"
-source "$(dirname "${BASH_SOURCE[0]}")/tools/u2-rpath-updater" 
-source "$(dirname "${BASH_SOURCE[0]}")/tools/u2-collect-ext-lib"
-
-run_if_not_dry() {
-    if [[ "$DRY_RUN" != "true" ]]; then
-        "$@"
-    else
-        color_echo "INFO" "Dry run mode: skipped: $*"
-    fi
-}
+source "$(dirname "${BASH_SOURCE[0]}")/tools/u2-core"
 
 build_universal2_python() {
     local python_version="$1"
     local custom_suffix="$2"
-    local no_clean="$3"
     local working_path="$PYENV_ROOT/versions"
     local temp_dir="$PYENV_ROOT/temp_dir/${custom_suffix}_temp"
     local output_dir="${working_path}/$custom_suffix"
@@ -32,13 +21,13 @@ build_universal2_python() {
     local arch_x86="$X86_ARCH"
     local arch_arm="$ARM_ARCH"
 
-    color_echo "INFO" "Step 1: Installing Python for x86_64..."
+    color_echo "INFO" "Installing Python for x86_64..."
     install_python_arch "$arch_x86" "$python_version" "$x86_brew_path" "${python_version}-x86" || {
         color_echo "ERROR" "Python x86_64 installation failed."
         exit 1
     }
    
-    color_echo "INFO" "Step 2: Installing Python for ARM64..."  
+    color_echo "INFO" "Installing Python for ARM64..."  
     install_python_arch "$arch_arm" "$python_version" "$arm_brew_path" "${python_version}-arm" || {
         color_echo "ERROR" "Python arm64 installation failed."
         exit 1
@@ -57,92 +46,104 @@ build_universal2_python() {
     local x86_dir="${working_path}/${python_version}-x86"
     local arm_dir="${working_path}/${python_version}-arm"
 
-    color_echo "INFO" "Step 3: Merging binary and collect dependencies..."
-    log "INFO" "Create environment"
+    color_echo "INFO" "Create environment"
     run_if_not_dry rsync -a "$arm_dir/" "$output_dir/"
+    local temp_metadata="$temp_dir/metadata"
     local temp_ext_collected_x86="$temp_dir/ext_lib_x86"
-    local temp_ext_collected_arm="$temp_dir/ext_lib_arm"
-    run_if_not_dry mkdir -p "$temp_dir/" "$target_path_ext" "$temp_ext_collected_x86" "$temp_ext_collected_arm"
+    local temp_int_collected_x86="$temp_dir/int_binary_x86"
+    run_if_not_dry mkdir -p "$temp_dir" "$target_path_ext" "$temp_metadata" "$temp_ext_collected_x86" "$temp_int_collected_x86"
 
-    path_regex
+    color_echo "INFO" "Scan binary & collect external binary"
+    local cache_scanner_target="$temp_metadata/scan_output.txt"
+    local cache_scanner_x86="$temp_metadata/scan_output_x86.txt"
+    local temp_merge_ext_metadata="$temp_metadata/merge_ext.txt"
+    local temp_merge_int_metadata="$temp_metadata/merge_int.txt"
+    local temp_collected_arm_metadata="$temp_metadata/collected_arm.txt"
+    local temp_collected_x86_metadata="$temp_metadata/collected_x86.txt"
+    scan_binary_and_cache "$output_dir" "$cache_scanner_target"
+    scan_binary_and_cache "$x86_dir" "$cache_scanner_x86"
 
-    log "INFO" "Create Fat Binary"
-    if [[ "$DRY_RUN" == "true" ]]; then
-        color_echo "INFO" "Dry run mode, skipping process."
-    else
-        local universal_binaries
-        universal_binaries=$(scan_binaries $output_dir)   
-        for binary in $universal_binaries; do
-            local relative_path="${binary#$output_dir/}"
-            local x86_binary="$x86_dir/$relative_path"
-            local merged_binary="$output_dir/$relative_path"
-            merge_int_bin_lib "$x86_binary" "$binary" "$merged_binary"        
-        done 
-    fi
-    
-    log "INFO" "Collect external dependencies"
-    if [[ "$DRY_RUN" == "true" ]]; then
-        color_echo "INFO" "Dry run mode, skipping process."
-    else
-        local saved_scan_log_output_fat="$temp_dir/${python_version}_scan_output_fat.txt" 
-        scan_and_extract_fat_binary "$output_dir" "$temp_dir" "$saved_scan_log_output_fat"
-        while IFS='|' read -r binary x86_binary arm_binary; do
-            color_echo "INFO" "collecting external binary."
-            process_collect_fat_ext_lib "$x86_binary" "$arm_binary" "$temp_ext_collected_x86" "$temp_ext_collected_arm"
-        done < "$saved_scan_log_output_fat"
+    while IFS=$'\n' read -r binary; do
+        collect_ext_lib "$binary" "$target_path_ext" "$temp_collected_arm_metadata"
+    done < "$cache_scanner_target"
+  
+    while IFS=$'\n' read -r binary; do
+        cp -p "$binary" "$temp_int_collected_x86"
+        collect_ext_lib "$binary" "$temp_ext_collected_x86" "$temp_collected_x86_metadata"
+    done < "$cache_scanner_x86"
 
-        color_echo "INFO" "update external binary rpath"
-        update_ext_lib "$temp_ext_collected_x86" "$target_path_ext"
-        update_ext_lib "$temp_ext_collected_arm" "$target_path_ext"
+    color_echo "INFO" "Update external binary LC_LOAD_DYLIB & LC_RPATH"
+    shopt -s nullglob
+    for ext_lib_x86 in "$temp_ext_collected_x86"/*; do
+        update_lc_load_dylib --binary="$ext_lib_x86" --ext="$target_path_ext"
+        update_lc_rpath --binary="$ext_lib_x86" --ext="$target_path_ext"
+    done
 
-        color_echo "INFO" "merging external binary rpath"
-        merge_ext_lib "$temp_ext_collected_x86" "$temp_ext_collected_arm" "$target_path_ext"
+    for ext_lib_arm in "$target_path_ext"/*; do
+        update_lc_load_dylib --binary="$ext_lib_arm" --ext="$target_path_ext"
+        update_lc_rpath --binary="$ext_lib_arm" --ext="$target_path_ext"
 
-        update_id_ext_binary "$target_path_ext" "@rpath/deps"
+        local relative_path="${ext_lib_arm#$target_path_ext/}"
+        local base_name_ext_lib=$(basename $relative_path)
+        local x86_ext_binary="$temp_ext_collected_x86/$base_name_ext_lib"
+        local merged_binary="$ext_lib_arm"
 
-        while IFS='|' read -r binary x86_binary arm_binary; do
-            color_echo "INFO" "update internal binary rpath"
-            update_int_fat_binary "$x86_binary" "$arm_binary" "$target_path_int" "$target_path_ext"
+        color_echo "INFO" "Merge external binary"
+        merge_binary_or_lib "$x86_ext_binary" "$ext_lib_arm" "$merged_binary" "$temp_merge_ext_metadata"
 
-            color_echo "INFO" "merging internal binary rpath"           
-            merge_int_bin_lib "$x86_binary" "$arm_binary" "$binary"
+        color_echo "INFO" "Update external LC_ID_DYLIB"
+        update_lc_id_dylib "$merged_binary" "@rpath/deps"
+    done
 
-            update_id_int_binary "$binary" "@rpath/lib"
-        done < "$saved_scan_log_output_fat"
+    for x86_int_binary in "$temp_int_collected_x86"/*; do
+        update_lc_load_dylib --binary="$x86_int_binary" --int="$target_path_int" --ext="$target_path_ext"
+        update_lc_rpath --binary="$x86_int_binary" --int="$target_path_int" --ext="$target_path_ext"
+    done
+    shopt -u nullglob
 
-        color_echo "INFO" "re-assign codedesign external binary"
-        resign_all_binaries "$target_path_ext"
-    fi
+    while IFS=$'\n' read -r binary; do
+        update_lc_load_dylib --binary="$binary" --int="$target_path_int" --ext="$target_path_ext"
+        update_lc_rpath --binary="$binary" --int="$target_path_int" --ext="$target_path_ext"
 
-    color_echo "INFO" "Step 4: Testing the fat binary..."
-    log "INFO" "test_binary_fat \"$output_dir\""
+        color_echo "INFO" "Merge internal binary"
+        local relative_path="${binary#$output_dir/}"
+        local base_name_binary=$(basename $relative_path)
+        local x86_int_binary="$temp_int_collected_x86/$base_name_binary"
+        local merged_binary="$binary"
+
+        merge_binary_or_lib "$x86_int_binary" "$binary" "$merged_binary" "$temp_merge_int_metadata"
+
+        color_echo "INFO" "Update internal LC_ID_DYLIB"
+        update_lc_id_dylib "$merged_binary" "@rpath/lib"
+    done < "$cache_scanner_target"
+
+    color_echo "INFO" "Resign codesign..."
+    resign_all_binaries "$target_path_ext"
+
+    color_echo "INFO" "test_binary_fat \"$output_dir\""
     test_binary_fat "$output_dir" || {
         if [[ "$DRY_RUN" == "true" ]]; then
-            color_echo "INFO" "Dry run mode, skipping test binary."
+                color_echo "INFO" "Dry run mode, skipping test binary."
         else
-            color_echo "ERROR" "Error: fat binary tests failed."
+            log "Error: fat binary tests failed."
             cleanup_temp "$output_dir"
-            cleanup_temp "$temp_dir"
+            cleanup_temp "$temp_dir" 
             exit 1
         fi
     }
-
-    color_echo "INFO" "Step 5: Cleaning up temporary installations..." 
+    color_echo "INFO" "Cleaning up temporary installations..." 
     if [[ "$DRY_RUN" == "true" ]]; then
             color_echo "INFO" "Dry run mode, skipping cleanup of temporary directories."
     else
-        if [[ $no_clean == false ]]; then               
+        if [[ $NO_CLEAN == false ]]; then               
             cleanup_temp "$x86_dir"
             cleanup_temp "$arm_dir"
             cleanup_temp "$temp_dir"
         else
             cleanup_temp "$temp_dir"
         fi
-        color_echo "INFO" "cleanup temporary file"
     fi
-
     color_echo "INFO" "Process completed"
-    
 }
 
 
diff --git a/libexec/universal2-rpath b/libexec/universal2-rpath
--- a/libexec/universal2-rpath
+++ b/libexec/universal2-rpath
@@ -1,38 +1,212 @@
 #!/usr/bin/env bash
+set -e
+
 source "$(dirname "${BASH_SOURCE[0]}")/tools/u2-utility"
-source "$(dirname "${BASH_SOURCE[0]}")/tools/u2-merge-lib-bin"
-source "$(dirname "${BASH_SOURCE[0]}")/tools/u2-rpath-updater"
+source "$(dirname "${BASH_SOURCE[0]}")/tools/u2-core"
 
-universal2_single_rpath(){
-    local python_dir="$1"   
-    local target_int_path="$2"
-    local target_ext_path="$3"
-    local target_id_path="$4"
-    local saved_scan_log="$5"
-
-    scan_binary_and_cache "$python_dir" "$saved_scan_log"
-    while IFS= read -r binary; do
-        update_int_binary "$binary" "$target_int_path" "$target_ext_path"
-        update_id_int_binary "$binary" "$target_id_path"
-    done < "$saved_scan_log"
-}
-
-universal2_fat_rpath() {
+single_update(){
     local python_dir="$1"   
     local temp_dir="$2"
-    local target_int_path="$3"
-    local target_ext_path="$4"
-    local target_id_path="$5"
-    local saved_scan_log="$6"
 
-    scan_and_extract_fat_binary "$python_dir" "$temp_dir" "$saved_scan_log"
-    while IFS='|' read -r binary x86_binary arm_binary; do
-        local binary_dir=$(dirname "$binary")
-        update_int_fat_binary "$x86_binary" "$arm_binary" "$target_int_path" "$target_ext_path"
-        merge_int_bin_lib "$x86_binary" "$arm_binary" "$binary"
-        update_id_int_binary "$binary" "$target_id_path"
-    done < "$saved_scan_log"
+    local only_int="false"
+    local only_ext="false"
 
+    for arg in "$@"; do
+        case $arg in
+            --int=*) only_int="${arg#*=}" ;;
+            --ext=*) only_ext="${arg#*=}" ;;
+            *)
+                log "WARN" "Unknown argument: $arg"
+                return 1
+                ;;
+        esac
+    done
+
+
+    local target_path_int target_path_ext
+    target_path_int=$(find "$python_dir" -type d -name "lib" 2>/dev/null | head -n 1)
+    target_path_ext=$(find "$python_dir" -type d -name "deps" 2>/dev/null | head -n 1)
+
+    if [[ -n "$target_path_ext" && -n "$target_path_int" ]]; then
+        local target_id_int_path="@rpath/$(basename "$target_path_int")"
+        local target_id_ext_path="@rpath/$(basename "$target_path_ext")"
+    fi
+
+    color_echo "INFO" "Create environment"
+    local temp_metadata="$temp_dir/metadata"
+    local temp_collected_binary="$temp_dir/collected_dir"
+    run_if_not_dry mkdir -p "$temp_dir" "$target_path_ext" "$temp_metadata" "$temp_collected_binary"
+
+    color_echo "INFO" "Scan binary & collect external binary"
+    local cache_scanner="$temp_metadata/scanner.txt"
+    local temp_merge_metadata="$temp_metadata/merge_bin.txt"
+    local temp_collected_metadata="$temp_metadata/collected_bin.txt"
+    scan_binary_and_cache "$python_dir" "$cache_scanner"
+
+    color_echo "INFO" "Update binary LC_LOAD_DYLIB, LC_RPATH, & LC_ID_DYLIB"
+    if [[ "$only_ext" == "true" ]]; then
+        if [[ -n "$target_path_ext" ]]; then
+            shopt -s nullglob
+            for binary in "$target_path_ext"/*; do
+                update_lc_load_dylib --binary="$binary" --ext="$target_path_ext"
+                update_lc_rpath --binary="$binary" --ext="$target_path_ext"
+                update_lc_id_dylib "$binary" "$target_id_ext_path"
+            done
+            shopt -u nullglob
+            resign_all_binaries "$target_path_ext"
+        else
+            color_echo "ERROR" "Missing external independent binary, plesae collect it first.."
+        fi
+        color_echo "INFO" "External-only update complete"
+        return 0
+    fi
+
+    while IFS=$'\n' read -r binary; do
+        if [[ "$only_int" == "true" ]]; then
+            [[ "$binary" == "$target_path_ext"* ]] && continue
+        fi
+
+        if [[ -n "$target_path_ext" && -n "$target_path_int" ]]; then
+            update_lc_load_dylib --binary="$binary" --int="$target_path_int" --ext="$target_path_ext"
+            update_lc_rpath --binary="$binary" --int="$target_path_int" --ext="$target_path_ext"
+        elif [[ -n "$target_path_ext" && -z "$target_path_int" ]]; then
+            update_lc_load_dylib --binary="$binary" --ext="$target_path_ext"
+            update_lc_rpath --binary="$binary" --ext="$target_path_ext"
+        elif [[ -z "$target_path_ext" && -n "$target_path_int" ]]; then
+            update_lc_load_dylib --binary="$binary" --int="$target_path_int"
+            update_lc_rpath --binary="$binary" --int="$target_path_int"
+        fi
+
+        if [[ "$binary" == "$target_path_ext"* ]]; then
+            update_lc_id_dylib "$binary" "$target_id_ext_path"
+            resign_all_binaries "$binary"
+        else
+            update_lc_id_dylib "$binary" "$target_id_int_path"
+        fi
+    done < "$cache_scanner"
+
+    color_echo "INFO" "All process completed"
+}
+
+fat_update() {
+    local python_dir="$1"   
+    local temp_dir="$2"
+
+    local only_int="false"
+    local only_ext="false"
+
+    for arg in "$@"; do
+        case $arg in
+            --int=*) only_int="${arg#*=}" ;;
+            --ext=*) only_ext="${arg#*=}" ;;
+            *)
+                log "WARN" "Unknown argument: $arg"
+                return 1
+                ;;
+        esac
+    done
+
+
+    local target_path_int target_path_ext
+    target_path_int=$(find "$python_dir" -type d -name "lib" 2>/dev/null | head -n 1)
+    target_path_ext=$(find "$python_dir" -type d -name "deps" 2>/dev/null | head -n 1)
+
+    if [[ -n "$target_path_ext" && -n "$target_path_int" ]]; then
+        local target_id_int_path="@rpath/$(basename "$target_path_int")"
+        local target_id_ext_path="@rpath/$(basename "$target_path_ext")"
+    fi
+
+    color_echo "INFO" "Create environment"
+    local temp_metadata="$temp_dir/metadata"
+    local temp_int_collected_arm="$temp_dir/int_binary_arm"
+    local temp_int_collected_x86="$temp_dir/int_binary_x86"
+    run_if_not_dry mkdir -p "$temp_dir" "$target_path_ext" "$temp_metadata" "$temp_int_collected_arm" "$temp_int_collected_x86"
+
+    color_echo "INFO" "Scan binary"
+    local cache_scanner="$temp_metadata/scan_python.txt"
+    local temp_merge_metadata="$temp_metadata/merge_binary.txt"
+    scan_binary_and_cache "$python_dir" "$cache_scanner"
+
+    color_echo "INFO" "Extract fat binary"
+    while IFS=$'\n' read -r binary; do
+        extract_fat_binary "$binary" "$temp_int_collected_arm" "$temp_int_collected_x86"
+    done < "$cache_scanner"
+
+    color_echo "INFO" "Update binary LC_LOAD_DYLIB, LC_RPATH, & LC_ID_DYLIB"
+    if [[ "$only_ext" == "true" ]]; then
+        if [[ -n "$target_path_ext" ]]; then
+            shopt -s nullglob
+            for arch_dir in "$temp_int_collected_x86" "$temp_int_collected_arm"; do
+                for binary in "$arch_dir"/*; do
+                    [[ "$binary" != "$target_path_ext"* ]] && continue
+                    update_lc_load_dylib --binary="$binary" --ext="$target_path_ext"
+                    update_lc_rpath      --binary="$binary" --ext="$target_path_ext"
+                done
+            done
+
+            for binary in "$target_path_ext"/*; do
+                local relative_path="${binary#$target_path_ext/}"
+                local base_name_ext_lib=$(basename $relative_path)
+                local arm_ext_binary="$temp_int_collected_arm/$base_name_ext_lib"
+                local x86_ext_binary="$temp_int_collected_x86/$base_name_ext_lib"
+                local merged_binary="$binary"
+
+                color_echo "INFO" "Merge external binary"
+                merge_binary_or_lib "$x86_ext_binary" "$arm_ext_binary" "$merged_binary" "$temp_merge_metadata"
+
+                color_echo "INFO" "Update external LC_ID_DYLIB"
+                update_lc_id_dylib "$merged_binary" "$target_id_ext_path"
+
+                resign_all_binaries "$merged_binary"
+            done
+            shopt -u nullglob
+        else
+            color_echo "ERROR" "Missing external independent binary, plesae collect it first.."
+        fi
+        color_echo "INFO" "External-only update complete"
+        return 0
+    fi
+
+    shopt -s nullglob
+    for arch_dir in "$temp_int_collected_x86" "$temp_int_collected_arm"; do
+        for binary in "$arch_dir"/*; do
+            [[ "$only_int" == "true" && "$binary" == "$target_path_ext"* ]] && continue
+
+            if [[ -n "$target_path_ext" && -n "$target_path_int" ]]; then
+                update_lc_load_dylib --binary="$binary" --int="$target_path_int" --ext="$target_path_ext"
+                update_lc_rpath      --binary="$binary" --int="$target_path_int" --ext="$target_path_ext"
+            elif [[ -n "$target_path_ext" ]]; then
+                update_lc_load_dylib --binary="$binary" --ext="$target_path_ext"
+                update_lc_rpath      --binary="$binary" --ext="$target_path_ext"
+            elif [[ -n "$target_path_int" ]]; then
+                update_lc_load_dylib --binary="$binary" --int="$target_path_int"
+                update_lc_rpath      --binary="$binary" --int="$target_path_int"
+            fi
+        done
+    done
+    shopt -u nullglob
+
+    while IFS=$'\n' read -r binary; do
+        [[ "$only_int" == "true" && "$binary" == "$target_path_ext"* ]] && continue
+
+        local relative_path="${binary#$python_dir/}"
+        local base_name_ext_lib=$(basename $relative_path)
+        local arm_binary="$temp_int_collected_arm/$base_name_ext_lib"
+        local x86_binary="$temp_int_collected_x86/$base_name_ext_lib"
+        local merged_binary="$binary"
+
+        color_echo "INFO" "Merge external binary"
+        merge_binary_or_lib "$x86_binary" "$arm_binary" "$merged_binary" "$temp_merge_metadata"
+
+        if [[ "$binary" == "$target_path_ext"* ]]; then
+            update_lc_id_dylib "$binary" "$target_id_ext_path"
+            resign_all_binaries "$merged_binary"
+        else
+            update_lc_id_dylib "$binary" "$target_id_int_path"
+        fi
+    done < "$cache_scanner"
+
+    color_echo "INFO" "All process completed"
 }
 
 universal2_update_rpath(){
@@ -40,40 +214,34 @@ universal2_update_rpath(){
     local python_dir="$2"   
     local temp_dir="$PYENV_ROOT/temp_dir/${python_version}_temp"
 
+    local only_int="false"
+    local only_ext="false"
+
+    for arg in "$@"; do
+        case $arg in
+            --int=*) only_int="${arg#*=}" ;;
+            --ext=*) only_ext="${arg#*=}" ;;
+            *)
+                log "WARN" "Unknown argument: $arg"
+                return 1
+                ;;
+        esac
+    done
+
     local minor_version
     minor_version="${python_version%.*}"
     local python_binary="$python_dir/bin/python${minor_version}"
 
-    local has_dep_collected
-    has_dep_collected=$(find "$working_path" -type d -name "$python_dir/deps" 2>/dev/null)
-    if [[ -n $has_dep_collected ]]; then
-        local target_int_path="$python_dir/lib"
-        local target_ext_path="$python_dir/deps"
-    else
-        local target_int_path="$python_dir/lib"
-        local target_ext_path="$python_dir/lib"
-    fi
-
-    local target_id_path="@rpath/lib"
-
     $DRY_RUN || mkdir -p "$temp_dir"
-    
-    path_regex
-
-    if [[ ! -f "$python_binary" ]]; then
-        log "ERROR" "Python binary not found at $python_binary"
-        return 1
-    fi
 
     if lipo -info "$python_binary" | grep -q "Non-fat"; then
         local saved_scan_log="$temp_dir/${python_version}_scan.txt"
-        universal2_single_rpath "$python_dir" "$target_int_path" "$target_ext_path" "$target_id_path" "$saved_scan_log"
+        single_update "$python_dir" "$temp_dir" --int="$only_int" --ext="$only_ext"
     else
         local saved_scan_log="$temp_dir/${python_version}_scan_extract.txt"
-        universal2_fat_rpath "$python_dir" "$temp_dir" "$target_int_path" "$target_ext_path" "$target_id_path" "$saved_scan_log"
+        fat_update "$python_dir" "$temp_dir" --int="$only_int" --ext="$only_ext"
     fi
 
     $DRY_RUN || cleanup_temp "$temp_dir"
     log "INFO" "Successfully updated all fat binaries in $python_dir"
-
 }
