Minor update (ver 1.2.0) with activate collect-lib command, restructure and remove unused rpath command

diff --git a/bin/pyenv-universal2 b/bin/pyenv-universal2
--- a/bin/pyenv-universal2
+++ b/bin/pyenv-universal2
@@ -64,7 +64,7 @@ color_echo() {
 # ====== Global Variable ======
 pyenv_universal2_config_path
 
-VERSION="1.1.2"
+VERSION="1.2.0"
 RELEASE_DATE="2025-02-09"
 PYENV_UNIVERSAL2_REPO="https://github.com/ziprangga/pyenv-universal2"
 DEBUG=false
@@ -79,7 +79,7 @@ readonly ARM_ARCH="arm64"
 PYENV_ROOT="${PYENV_ROOT:-$(pyenv root)}"
 readonly PYENV_ROOT
 readonly BASE_COMMAND="pyenv-universal2"
-readonly commands=("build" "merge" "arm64" "x86_64" "collect-deps" "rpath-update" "test" "update" "version" "custom-brew" "help")
+readonly commands=("build" "merge" "arm64" "x86_64" "collect-lib" "test" "update" "version" "custom-brew" "help")
 
 # ====== Load Core Script ======
 load_core_script() {
@@ -263,12 +263,12 @@ test_command() {
     universal2_test "$python_version"
 }
 
-collect-deps_command() {
+collect-lib_command() {
     local python_version="$1"
     shift
 
      if [[ -z "$python_version" ]]; then
-        color_echo "ERROR" "Error: 'collect-deps' requires at least one argument." >&2
+        color_echo "ERROR" "Error: 'collect-lib' requires at least one argument." >&2
         exit 1
     fi
 
@@ -285,44 +285,6 @@ collect-deps_command() {
     fi
  
     universal2_collect_binary "$python_version" "$python_dir"
-}
-
-rpath-update_command() {
-    local python_version="$1"
-    shift
-
-    local only_int="false"
-    local only_ext="false"
-
-    for arg in "$@"; do
-        case $arg in
-            --int=*) only_int="${arg#*=}" ;;
-            --ext=*) only_ext="${arg#*=}" ;;
-            *)
-                log "WARN" "Unknown argument: $arg"
-                return 1
-                ;;
-        esac
-    done
-
-     if [[ -z "$python_version" ]]; then
-        color_echo "ERROR" "Error: 'rpath' requires at least one argument (python version)." >&2
-        exit 1
-    fi
-
-    local python_dir
-    if [[ $# -gt 0 ]]; then
-        python_dir="$1"
-    else
-        python_dir="$PYENV_ROOT/versions/$python_version"
-    fi
-
-    if ! declare -F universal2-rpath >/dev/null; then
-        log "INFO" "Loading core script for change rpath python"
-        load_core_script "universal2-rpath"
-    fi
- 
-    universal2_update_rpath "$python_version" "$python_dir" --int="$only_int" --ext="$only_ext"
 }
 
 update_command() {
@@ -382,6 +344,8 @@ help_command() {
     echo "  merge             Merge single binaries into a universal binary"
     echo "  arm64             Build a single binary for ARM64"
     echo "  x86_64            Build a single binary for x86_64"
+    echo "  collect-lib       Collect external library"
+    echo "  custom-brew       Add custom homebrew path"
     echo "  version           Show version information"
     echo "  help              Show this help message"
     echo "  test              Test the built binaries"
@@ -392,6 +356,7 @@ command_dispatcher() {
     local COMMAND="$1"
     shift
 
+    log "INFO" "$@"
     if [[ " ${commands[*]} " =~ " $COMMAND " ]]; then
         "${COMMAND}_command" "$@"
     else
